title: Ben Mancell
logo: bmancell_coverphotoBW.jpg
description: <i>GIS Manager @NYC_Buildings<br/>Web Map Applications<br/>Interactive Dashboards<br/>Data Visualization<br/>Data Analytics</i>
theme: jekyll-theme-minimal
